---
dependencies: []

galaxy_info:
  role_name: mysql
  author: geerlingguy
  description: MySQL server for RHEL/CentOS and Debian/Ubuntu.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 6
        - 7
        - 8
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Archlinux
      versions:
        - all
  galaxy_tags:
    - database
    - mysql
    - mariadb
    - db
    - sql
