---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Fail2Ban
- include_tasks: fail2ban-RedHat.yml
  when: ansible_os_family == 'RedHat' and security_fail2ban_enabled

- include_tasks: fail2ban-Debian.yml
  when: ansible_os_family == 'Debian' and security_fail2ban_enabled

- name: Ensure fail2ban is running and enabled on boot.
  service: name=fail2ban state=started enabled=yes
  when: security_fail2ban_enabled

# SSH
- include_tasks: ssh.yml

# Autoupdate
- include_tasks: autoupdate-RedHat.yml
  when: ansible_os_family == 'RedHat' and security_autoupdate_enabled

- include_tasks: autoupdate-Debian.yml
  when: ansible_os_family == 'Debian' and security_autoupdate_enabled
