---
- name: Converge
  hosts: all
  become: true

  vars:
    solr_version: "4.10.4"
    solr_remove_cruft: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == "Debian"

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.solr
