---
- name: clear opcache
  shell: >
    cd {{ drupal_core_path }} &&
    {{ drush_path }} eval "if (function_exists('apc_clear_cache')) { apc_clear_cache(); }; if (function_exists('opcache_reset')) { opcache_reset(); }"
