---
sudo: required

env:
  global:
    - CONFIG: tests/config.yml
      MAKEFILE: example.drupal.make.yml
      COMPOSERFILE: example.drupal.composer.json
      HOSTNAME: drupalvm.dev
      MACHINE_NAME: drupalvm
      IP: 192.168.88.88
      DRUPALVM_DIR: /var/www/drupalvm
  matrix:
    - distribution: ubuntu
      version: 16.04
      init: /sbin/init
      run_opts: "--privileged"
    - distribution: ubuntu
      version: 16.04
      init: /sbin/init
      run_opts: "--privileged"
      local_config: tests/ubuntu-16-nginx.config.yml
      config_dir: /var/www/drupalvm/config
    - distribution: centos
      version: 7
      init: /usr/lib/systemd/systemd
      run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

services:
  - docker

before_install:
  # Pull container
  - 'sudo docker pull ${distribution}:${version}'
  # Customize container
  - 'sudo docker build --rm=true --file=tests/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible tests'
  # Install lint tools.
  - 'gem install rubocop'

script:
  - container_id=$(mktemp)

  # Run container in detached state
  - 'sudo docker run --detach --volume="${PWD}":${DRUPALVM_DIR}/:rw ${run_opts} ${distribution}-${version}:ansible "${init}" > "${container_id}"'

  # Set hostname.
  - 'sudo docker exec "$(cat ${container_id})" hostname ${HOSTNAME}'

  # Setup directories.
  - 'sudo docker exec "$(cat ${container_id})" mkdir -p ${DRUPALVM_DIR}/drupal'

  # Install dependencies.
  - 'sudo docker exec "$(cat ${container_id})" ansible-galaxy install -r ${DRUPALVM_DIR}/provisioning/requirements.yml'

  # Setup config directory.
  - '[[ ! -z "${config_dir}" ]] && sudo docker exec "$(cat ${container_id})" mkdir -p ${config_dir} || true'

  # Copy configuration files into place.
  - 'sudo docker exec "$(cat ${container_id})" cp ${DRUPALVM_DIR}/${CONFIG} ${config_dir:-$DRUPALVM_DIR}/config.yml'
  - 'sudo docker exec "$(cat ${container_id})" cp ${DRUPALVM_DIR}/${MAKEFILE} ${config_dir:-$DRUPALVM_DIR}/drupal.make.yml'
  - 'sudo docker exec "$(cat ${container_id})" cp ${DRUPALVM_DIR}/${COMPOSERFILE} ${config_dir:-$DRUPALVM_DIR}/drupal.composer.json'

  # Override configuration variables.
  - '[[ ! -z "${local_config}" ]] && sudo docker exec "$(cat ${container_id})" bash -c "cp ${DRUPALVM_DIR}/${local_config} ${config_dir:-$DRUPALVM_DIR}/local.config.yml" || true'

  # Vagrantfile syntax check
  - 'rubocop --except LineLength,Eval,MutableConstant'

  # Ansible syntax check.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook ${DRUPALVM_DIR}/provisioning/playbook.yml --syntax-check'

  # Run the playbook with ansible-playbook.
  - >
    if [ ! -z "${config_dir}" ]; then
      sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook ${DRUPALVM_DIR}/provisioning/playbook.yml --extra-vars="config_dir=${config_dir}";
    else
      sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook ${DRUPALVM_DIR}/provisioning/playbook.yml;
    fi

  # Run the integration tests
  - >
    sudo docker exec "$(cat ${container_id})" curl -s --header Host:${HOSTNAME} localhost
    | grep -q '<title>Welcome to Drupal'
    && (echo 'Drupal install pass' && exit 0)
    || (echo 'Drupal install fail' && exit 1)

  - >
    sudo docker exec "$(cat ${container_id})" curl -s --header Host:adminer.${HOSTNAME} localhost
    | grep -q '<title>Login - Adminer'
    && (echo 'Admin install pass' && exit 0)
    || (echo 'Adminer install fail' && exit 1)

  - >
    sudo docker exec "$(cat ${container_id})" curl -s --header Host:pimpmylog.${HOSTNAME} localhost
    | grep -q '<title>Pimp my Log'
    && (echo 'Pimp my Log install pass' && exit 0)
    || (echo 'Pimp my Log install fail' && exit 1)

  - >
    sudo docker exec "$(cat ${container_id})" curl -s --header Host:xhprof.${HOSTNAME} localhost
    | grep -q '<title>XHProf'
    && (echo 'XHProf install pass' && exit 0)
    || (echo 'XHProf install fail' && exit 1)

  - >
    sudo docker exec "$(cat ${container_id})" curl -s localhost:8025
    | grep -q '<title>MailHog'
    && (echo 'MailHog install pass' && exit 0)
    || (echo 'MailHog install fail' && exit 1)

  - >
    sudo docker exec "$(cat ${container_id})" curl -s --header Host:${IP} localhost
    | grep -q "<li>${IP} ${HOSTNAME}</li>"
    && (echo 'Dashboard install pass' && exit 0)
    || (echo 'Dashboard install fail' && exit 1)

  - >
    sudo docker exec "$(cat ${container_id})" drush @${MACHINE_NAME}.${HOSTNAME} status
    | grep -q 'Drupal bootstrap.*Successful'
    && (echo 'Drush install pass' && exit 0)
    || (echo 'Drush install fail' && exit 1)

  # Clean up
  - 'sudo docker stop "$(cat ${container_id})"'
