site_name: Drupal VM Documentation

repo_url: https://github.com/geerlingguy/drupal-vm
site_description: 'Drupal VM - A VM for local Drupal development, built with Vagrant + Ansible'
theme: readthedocs

extra_javascript:
  - js/fix_search.js

markdown_extensions:
  - toc:
      permalink: True

pages:
  - Home: 'index.md'
  - Getting Started:
    - Installation:
      - 'macOS': 'getting-started/installation-macos.md'
      - 'Windows': 'getting-started/installation-windows.md'
      - 'Linux': 'getting-started/installation-linux.md'
    - 'Configuring Drupal VM': 'getting-started/configure-drupalvm.md'
    - 'Syncing Folders': 'getting-started/syncing-folders.md'
  - Building your codebase:
    - 'Using a local Drupal codebase': 'deployment/local-codebase.md'
    - 'Using a composer package': 'deployment/composer-package.md'
    - 'Using composer.json': 'deployment/composer.md'
    - 'Using a Drush Make file': 'deployment/drush-make.md'
    - 'Drupal VM as a Composer Dependency': 'deployment/composer-dependency.md'
    - 'Deploying Drupal via Git': 'deployment/git.md'
  - Basic configurations:
    - 'Using different base OSes': 'configurations/base-os.md'
    - 'Using a different PHP version': 'configurations/php.md'
    - Webservers:
      - 'Apache': 'configurations/webservers-apache.md'
      - 'Nginx': 'configurations/webservers-nginx.md'
    - Databases:
      - 'Connect to the MySQL Database': 'configurations/databases-mysql.md'
      - 'Use MariaDB instead of MySQL': 'configurations/databases-mariadb.md'
      - 'Use PostgreSQL instead of MySQL': 'configurations/databases-postgresql.md'
  - Installed extras:
    - 'adminer (Database UI)': 'extras/adminer.md'
    - 'blackfire (Profiling tool)': 'extras/blackfire.md'
    - 'drupalconsole (Drupal CLI)': 'extras/drupal-console.md'
    - 'drush (Drupal CLI)': 'extras/drush.md'
    - 'elasticsearch (Search engine)': 'extras/elasticsearch.md'
    - 'java': 'extras/java.md'
    - 'mailhog (Mail catcher)': 'extras/mailhog.md'
    - 'memcached (In-memory cache)': 'extras/memcached.md'
    - 'newrelic (Performance monitoring)': 'extras/newrelic.md'
    - 'nodejs': 'extras/nodejs.md'
    - 'pimpmylog (Log viewer)': 'extras/pimpmylog.md'
    - 'redis (In-memory database)': 'extras/redis.md'
    - 'ruby': 'extras/ruby.md'
    - 'selenium (BDD with Behat)': 'extras/selenium.md'
    - 'solr (Search engine)': 'extras/solr.md'
    - 'tidways (Profiling tool)': 'extras/tideways.md'
    - 'upload-progress': 'extras/upload-progress.md'
    - 'varnish (Caching reverse proxy)': 'extras/varnish.md'
    - 'xdebug (Debugging tool)': 'extras/xdebug.md'
    - 'xhprof (Profiling tool)': 'extras/xhprof.md'
  - Extending Drupal VM:
    - 'Adding Vagrant plugins Vagrantfile.local': 'extending/vagrantfile.md'
    - 'Passing on CLI arguments to ansible': 'extending/ansible-args.md'
    - 'Pre- and Post-Provision Scripts': 'extending/scripts.md'
  - Other Information:
    - 'Networking Notes': 'other/networking.md'
    - 'Vagrant LXC provider': 'other/vagrant-lxc.md'
    - 'Improving Performance': 'other/performance.md'
    - 'Docker': 'other/docker.md'
    - 'BigPipe with Drupal VM': 'other/bigpipe.md'
    - 'Drupal multisite': 'deployment/multisite.md'
    - 'Drupal 6 Notes': 'other/drupal-6.md'
    - 'Drupal VM Management Tools': 'other/management-tools.md'
    - 'Emulating Acquia Cloud environment': 'other/acquia.md'
    - 'Deploying to a production environment': 'other/production.md'
    - 'Wordpress or other applications': 'other/wordpress-other-applications.md'
