---
workspace: /root

php_xdebug_version: 2.5.0

php_xdebug_coverage_enable: 1
php_xdebug_default_enable: 1
php_xdebug_cli_enable: 1

php_xdebug_remote_enable: "false"
php_xdebug_remote_connect_back: "false"
php_xdebug_remote_host: localhost
php_xdebug_remote_port: "9000"
php_xdebug_remote_log: /tmp/xdebug.log
php_xdebug_remote_autostart: "false"

php_xdebug_idekey: sublime.xdebug

php_xdebug_max_nesting_level: 256

