---
services: docker

env:
  # Test current version of Solr on latest supported OSes.
  - distro: centos7
    playbook: test-solr-6.yml
  - distro: ubuntu1604
    playbook: test-solr-6.yml
  - distro: debian8
    playbook: test-solr-6.yml

  # Test older versions of Solr / OSes.
  - distro: ubuntu1404
    playbook: test-solr-5.yml
  - distro: ubuntu1204
    playbook: test-solr-5.yml
  - distro: ubuntu1404
    playbook: test-solr-4.yml
  - distro: ubuntu1404
    playbook: test-solr-3.yml

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Make sure Solr is running.
  - >
    sudo docker exec ${container_id} ps -ax | grep -q 'solr'
    && (echo 'solr is running: pass' && exit 0)
    || (echo 'solr is running: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
