---
dependencies: []

galaxy_info:
  author: geerlingguy
  description: Apache Solr for Linux.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.2
  platforms:
    - name: EL
      versions:
      - 6
      - 7
    - name: Debian
      versions:
      - all
    - name: Ubuntu
      versions:
      - all
  galaxy_tags:
    - development
