---
language: python
services: docker

env:
  global:
    - ROLE_NAME: php-versions
  matrix:
    # Default PHP version (7.3).
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian10

    # PHP 7.4.
    - MOLECULE_DISTRO: centos8
      MOLECULE_DOCKER_COMMAND: /usr/lib/systemd/systemd
      MOLECULE_PLAYBOOK: playbook-7.4.yml
    - MOLECULE_DISTRO: ubuntu1804
      MOLECULE_PLAYBOOK: playbook-7.4.yml
    - MOLECULE_DISTRO: debian10
      MOLECULE_PLAYBOOK: playbook-7.4.yml

    # PHP 7.2.
    - MOLECULE_DISTRO: centos8
      MOLECULE_PLAYBOOK: playbook-7.2.yml
    - MOLECULE_DISTRO: ubuntu1804
      MOLECULE_PLAYBOOK: playbook-7.2.yml

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME geerlingguy.$ROLE_NAME
  - cd geerlingguy.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
