---
dependencies: []

galaxy_info:
  author: geerlingguy
  description: PHP for RedHat/CentOS/Debian/Ubuntu.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  galaxy_tags:
    - development
    - web
