---
dependencies: []

galaxy_info:
  role_name: php
  author: geerlingguy
  description: PHP for RedHat/CentOS/Fedora/Debian/Ubuntu.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 6
        - 7
        - 8
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
  galaxy_tags:
    - development
    - web
    - php
    - language
    - fpm
    - drupal
    - wordpress
    - joomla
    - magento
