---
- name: Check current list of Solr cores.
  uri:
    url: http://{{ solr_connect_host }}:{{ solr_port }}/solr/admin/cores
    return_content: true
  register: solr_cores_current
  check_mode: false

- name: Ensure Solr conf directories exist.
  file:
    path: "{{ solr_home }}/data/{{ item }}/conf"
    state: directory
    owner: "{{ solr_user }}"
    group: "{{ solr_user }}"
    recurse: true
    mode: 0755
  when: "item not in solr_cores_current.content"
  with_items: "{{ solr_cores }}"

- name: Ensure core configuration directories exist.
  command: "cp -r {{ solr_install_path }}/example/files/conf/ {{ solr_home }}/data/{{ item }}/"
  when: "item not in solr_cores_current.content"
  with_items: "{{ solr_cores }}"
  become: true
  become_user: "{{ solr_user }}"

- name: Create configured cores.
  command: "{{ solr_install_path }}/bin/solr create -c {{ item }} -p {{ solr_port }}"
  when: "item not in solr_cores_current.content"
  with_items: "{{ solr_cores }}"
  become: true
  become_user: "{{ solr_user }}"
