---
- name: Add backwards-compatibility shims.
  include: backwards-compatibility.yml
  static: no

- name: Check if Drupal is already set up.
  stat: "path={{ drupal_core_path }}/index.php"
  register: drupal_site
  ignore_errors: true

- name: Define drupal_site_exists
  set_fact:
    drupal_site_exists: "{{ drupal_site.stat.exists|default(false) }}"

# Build makefile if configured.
- include: tasks/build-makefile.yml
  when: drupal_build_makefile

# Build with composer if configured.
- include: tasks/build-composer.yml
  when: drupal_build_composer

# Build a composer project if configured.
- include: tasks/build-composer-project.yml
  when: drupal_build_composer_project

# Set Drush variables.
- name: Check if a project specific Drush binary exists.
  stat: "path={{ drupal_composer_install_dir }}/vendor/drush/drush/drush"
  register: drush_vendor_bin
  ignore_errors: true

- name: Use project specific Drush if available.
  set_fact:
    drush_path: "{{ drupal_composer_install_dir }}/vendor/drush/drush/drush"
  when: drush_vendor_bin.stat.exists

# Install site if configured.
- include: tasks/install-site.yml
  when: drupal_install_site
