---
dependencies:
  - geerlingguy.php

galaxy_info:
  author: geerlingguy
  description: PHP Memcached support for Linux
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 1.8
  platforms:
    - name: EL
      versions:
      - 6
      - 7
    - name: Debian
      versions:
      - all
    - name: Ubuntu
      versions:
      - all
  galaxy_tags:
    - database
    - web
