---
dependencies: []

galaxy_info:
  author: geerlingguy
  description: Deploy or install Drupal on your servers.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
      - all
    - name: Ubuntu
      versions:
      - all
    - name: Debian
      versions:
      - all
  galaxy_tags:
    - development
    - web
    - drupal
    - cms
    - php
