---
- name: Converge
  hosts: all
  become: true

  vars:
    php_enable_webserver: false
    php_default_version_debian: "7.3"
    php_pecl_install_pecl: true
    php_pecl_extensions:
      - redis

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Install development tools (Debian).
      apt: name=build-essential state=present
      when: ansible_os_family == 'Debian'

    - name: Install development tools (RedHat).
      yum: name="@Development tools" state=present
      when: ansible_os_family == 'RedHat'

  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - role: geerlingguy.php-versions
    - role: geerlingguy.php
    - role: geerlingguy.php-pecl

  post_tasks:
    - name: Run test script to confirm Redis extension is available to PHP.
      script: pecl-test.php
      args:
        executable: php
      changed_when: false
