---
solr_workspace: /root

solr_create_user: true
solr_user: solr

solr_version: "6.3.0"
solr_mirror: "https://archive.apache.org/dist"
solr_remove_cruft: false

solr_service_name: solr
solr_install_dir: /opt
solr_install_path: "/opt/{{ solr_service_name }}"
solr_home: "/var/{{ solr_service_name }}"
solr_connect_host: localhost
solr_port: "8983"

solr_xms: "256M"
solr_xmx: "512M"

solr_timezone: "UTC"

solr_cores:
  - collection1

solr_config_file: /etc/default/{{ solr_service_name }}.in.sh

# Enable restart solr handler
solr_restart_handler_enabled: true

# Used only for Solr < 5.
solr_log_file_path: /var/log/solr.log
solr_host: "0.0.0.0"
