---
services: docker

env:
  # Composer-project-based Drupal 8 site setup.
  - distro: centos7
    playbook: test.yml
  - distro: debian8
    playbook: test.yml
  - distro: ubuntu1604
    playbook: test.yml
  - distro: ubuntu1404
    playbook: test.yml
  # Git-based Drupal 8 site setup.
  - distro: centos7
    playbook: test-deploy.yml

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Make sure Drupal is running.
  - 'docker exec --tty ${container_id} env TERM=xterm curl http://drupaltest.dev/ | grep "Welcome to Drupal"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
