---
drush_install_path: /usr/local/share/drush
drush_path: /usr/local/bin/drush
drush_version: "master"
drush_keep_updated: no
drush_force_update: no

drush_composer_cli_options: "--prefer-dist --no-interaction"
drush_clone_depth: 1
