---
- name: Converge
  hosts: all
  become: true

  vars:
    php_enable_webserver: false
    php_version: '7.4'

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - role: geerlingguy.php-versions
    - role: geerlingguy.php

  post_tasks:
    - name: Confirm PHP version is correct.
      shell: php -v | grep -F '{{ php_version }}'
      changed_when: false
