---
dependencies: []

galaxy_info:
  author: geerlingguy
  description: Git version control software
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - development
    - system
    - git
    - vcs
    - source
    - code
