---
# Normally, this would be set to the hostname of your DigitalOcean Droplet.
drupal_domain: "drupalvm.dev"
vagrant_hostname: "{{ drupal_domain }}"

# Add only the `apache_vhosts` or `nginx_vhosts` you need. If installing a
# single Drupal site, the variable should look like this (Apache):
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

# Since this will be a publicly-accessible instance of Drupal VM, make sure you
# configure secure passwords, especially for Drupal and MySQL!
drupal_account_pass: admin
drupal_db_password: drupal
mysql_root_password: root

# Only install extras that you will need/use on your site, and don't install
# development-related software on production environments!
installed_extras:
  - drush
  # - memcached
  # - redis
  # - solr
  - varnish

# Disable Apache package upgrades.
apache_packages_state: installed

# Disable the dashboard page. Also remove any unneeded virtualhosts.
dashboard_install_dir: ''

# Enable a more hardened security configuration.
extra_security_enabled: true

# Restrict the firewall to only ports that are required for external services.
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"
firewall_log_dropped_packets: true

# Set Apache to listen on port 81 (internal only), and Varnish on 80.
apache_listen_port: "81"
varnish_listen_port: "80"
varnish_default_backend_port: "81"
