---
dependencies: []

galaxy_info:
  author: geerlingguy
  description: Redis for Linux
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
      - 6
      - 7
    - name: Fedora
      versions:
      - all
    - name: Debian
      versions:
      - all
    - name: Ubuntu
      versions:
      - all
    - name: Archlinux
      versions:
      - all
  galaxy_tags:
    - database
    - development
    - web
