---
elasticsearch_version: '6.x'
elasticsearch_package_state: present

elasticsearch_service_state: started
elasticsearch_service_enabled: true

elasticsearch_network_host: localhost
elasticsearch_http_port: 9200
