---
- name: Ensure configured cron jobs exist in root account's crontab.
  cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute | default('*') }}"
    hour: "{{ item.hour | default('*') }}"
    day: "{{ item.day | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
    month: "{{ item.month | default('*') }}"
    job: "{{ item.job }}"
    state: "{{ item.state | default('present') }}"
  with_items: drupalvm_cron_jobs
  when: drupalvm_cron_jobs is defined
