---
- name: Get software for Python-based control.
  yum: "name={{ item }} state=installed"
  with_items:
    - "curl"
    - "python-pycurl"
    - "@development"
    - "unzip"

- name: Enable remi repo for MySQL.
  set_fact: mysql_enablerepo="remi"
  when: mysql_enablerepo is not defined or mysql_enablerepo == ""

- name: Enable remi repo for PHP 5.5.
  set_fact: php_enablerepo="remi,remi-php55"
  when: php_version == "5.5"

- name: Enable remi repo for PHP 5.6.
  set_fact: php_enablerepo="remi,remi-php56"
  when: php_version == "5.6"

- name: Enable remi repo for PHP 7.0.
  set_fact: php_enablerepo="remi,remi-php70"
  when: php_version == "7.0"

- name: Enable remi repo for PHP 7.1
  set_fact: php_enablerepo="remi,remi-php71"
  when: php_version == "7.1"

- name: Define php_xhprof_html_dir.
  set_fact:
    php_xhprof_html_dir: "/usr/share/pear/xhprof_html"
  when: php_xhprof_html_dir is not defined
