---
- name: Update apt cache if needed.
  apt: update_cache=yes cache_valid_time=86400

- name: Get software for Python-based control.
  apt: "name={{ item }} state=installed"
  with_items:
    - curl
    - python-apt
    - python-pycurl
    - build-essential
    - sudo
    - unzip

- name: Disable the ufw firewall (since we use a simple iptables firewall).
  service: name=ufw state=stopped
  when: ansible_distribution == "Ubuntu" and {{ drupalvm_disable_ufw_firewall | default(true) }}

- name: Add repository for Apache 2.4 on Ubuntu 12.
  apt_repository: repo='ppa:ondrej/apache2'
  when: ansible_distribution_release == "precise" and ansible_distribution == "Ubuntu"

- name: Add repository for PHP 5.5, 5.6 or 7.0.
  apt_repository: repo='ppa:ondrej/php'
  when: >
    (php_version == "5.5" or php_version == "5.6" or php_version == "7.0") and
    ansible_distribution == "Ubuntu" and
    ansible_distribution_version != "16.04"

- name: Define php_xhprof_html_dir.
  set_fact:
    php_xhprof_html_dir: "/usr/share/php/xhprof_html"
  when: php_xhprof_html_dir is not defined
