---
- name: Update apt cache if needed.
  apt: update_cache=yes cache_valid_time=86400

- name: Get software for Python-based control.
  apt: "pkg={{ item }} state=installed"
  with_items:
  - curl
  - python-apt
  - python-pycurl
  - build-essential

- name: Disable the firewall (since this is for local dev only).
  service: name=ufw state=stopped

- name: Add repository for PHP 5.5 on Ubuntu 12.04.
  # Note: Add '-oldstable' for PHP 5.4, if desired.
  apt_repository: repo='ppa:ondrej/php5'

- name: Install postfix so Drupal can send emails.
  apt: pkg=postfix state=installed

- name: Add drupal_domain to the hosts file.
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1  {{ drupal_domain }}$"
    line: "127.0.0.1  {{ drupal_domain }}"
    state: present
