---
- name: Disable MySQL AppArmor profile.
  file:
    path: /etc/apparmor.d/disable/usr.sbin.mysqld
    src: /etc/apparmor.d/usr.sbin.mysqld
    state: link
  register: mysql_apparmor
  when: not extra_security_enabled

- name: Restart AppArmor.
  service: name=apparmor state=restarted
  when: mysql_apparmor.changed
