---
- name: Do not accept locale environment variables passed over SSH.
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^AcceptEnv LANG"
    state: absent
    validate: "/usr/sbin/sshd -T -f %s"

- name: Check if local known_hosts file is present.
  stat: "path={{ known_hosts_path | default('~/.ssh/known_hosts') }}"
  register: known_hosts_file
  connection: local
  sudo: no

- name: Copy known_hosts file from host into Drupal VM.
  copy:
    src: "{{ known_hosts_path | default('~/.ssh/known_hosts') }}"
    dest: ~/.ssh/known_hosts
    mode: 0644
  sudo: no
  when: known_hosts_file.stat.exists
