---
- hosts: all

  vars_files:
    - ../config.yml

  pre_tasks:
    - include: tasks/init-debian.yml
      when: ansible_os_family == 'Debian'
    - include: tasks/init-redhat.yml
      when: ansible_os_family == 'RedHat'

  roles:
    # Essential roles.
    - { role: geerlingguy.repo-remi, when: ansible_os_family == 'RedHat' }
    - geerlingguy.firewall
    - geerlingguy.git
    - geerlingguy.postfix
    - geerlingguy.apache
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.php-pecl
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.drush
    - { role: geerlingguy.drupal-console, when: drupal_major_version > 7 }

    # Conditionally-installed roles.
    - { role: geerlingguy.memcached, when: '"memcached" in installed_extras' }
    - { role: geerlingguy.php-memcached, when: '"memcached" in installed_extras' }
    - { role: geerlingguy.php-xdebug, when: '"xdebug" in installed_extras' }
    - { role: geerlingguy.php-xhprof, when: '"xhprof" in installed_extras' }
    - { role: geerlingguy.adminer, when: '"adminer" in installed_extras' }
    - { role: geerlingguy.pimpmylog, when: '"pimpmylog" in installed_extras' }
    - { role: geerlingguy.daemonize, when: '"mailhog" in installed_extras' }
    - { role: geerlingguy.mailhog, when: '"mailhog" in installed_extras' }
    - { role: geerlingguy.nodejs, when: '"nodejs" in installed_extras' }
    - { role: geerlingguy.ruby, when: '"ruby" in installed_extras' }
    - { role: geerlingguy.java, when: '"solr" in installed_extras or "selenium" in installed_extras' }
    - { role: arknoll.selenium, when: '"selenium" in installed_extras' }
    - { role: geerlingguy.solr, when: '"solr" in installed_extras' }
    - { role: geerlingguy.varnish, when: '"varnish" in installed_extras' }

    # Roles for security and stability on production.
    - { role: geerlingguy.security, when: extra_security_enabled }

  tasks:
    - name: Check if Drupal is already set up.
      stat: "path={{ drupal_core_path }}/index.php"
      register: drupal_site

    - include: tasks/sshd.yml
    - include: tasks/extras.yml
    - include: tasks/www.yml
    - include: tasks/apparmor.yml
      when: ansible_os_family == 'Debian'

    # Build makefile if configured.
    - include: tasks/build-makefile.yml
      when: build_makefile

    # Install site if configured.
    - include: tasks/install-site.yml
      when: install_site

    - include: tasks/drush-aliases.yml
    - include: tasks/cron.yml
