---
- hosts: all

  vars_files:
    - ../config.yml

  pre_tasks:
    - include: tasks/init.yml

  roles:
    - { role: geerlingguy.firewall, tags: ['firewall'] }
    - { role: geerlingguy.git, tags: ['git'] }
    - { role: geerlingguy.apache, tags: ['apache'] }
    - { role: geerlingguy.mysql, tags: ['mysql'] }
    - { role: geerlingguy.php, tags: ['php'] }
    - { role: geerlingguy.php-pecl, tags: ['php'] }
    - { role: geerlingguy.php-mysql, tags: ['php'] }
    - { role: geerlingguy.php-xdebug, tags: ['php'] }
    - { role: geerlingguy.php-xhprof, tags: ['php'] }
    - { role: geerlingguy.composer, tags: ['composer'] }
    - { role: geerlingguy.drush, tags: ['drush'] }
    - { role: geerlingguy.daemonize, tags: ['mail'] }
    - { role: geerlingguy.mailhog, tags: ['mail'] }

  tasks:
    - include: tasks/www.yml
    - include: tasks/drupal.yml
