---
dependencies: []

galaxy_info:
  author: geerlingguy
  description: PostgreSQL server for Linux.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - database
    - postgresql
    - postgres
    - rdbms
